title = "Jason Nedell - Software Developer 😎"
description = "I’m Jason, a software developer and maker. I design and build creations, large & small, digital & physical."
base_url = "https://nedell.com"
compile_sass = true
